# Module: PedidosCab
# Document : modules/PedidosCab/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 22.02.2015 14:40:48
#
---
PedidosCab:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IdSucursal
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IdSucursal
  fieldGeneratorMetatagDescription: IdSucursal
  fieldGeneratorMetatagKeywords: IdSucursal
  controller: PedidosCab
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Pedidos
  id_video: pedidoscab
  url_video: null
  feature_list: YES
  entity: PedidosCab
  table: AgtPedidosCab
  primarykey: Id
  linkBy: ''
  records_per_page: 10
  export: 'false'
  order_by:
    -
      title: 'N.Pedido z-a'
      criteria: 'Id DESC'      
    -
      title: 'N.Pedido a-z'
      criteria: 'Id ASC'
    -
      title: 'Fecha z-a'
      criteria: 'Fecha DESC'      
    -
      title: 'Fecha a-z'
      criteria: 'Fecha ASC'
  search_default: Id
  referenced_entities:
    - Sucursales
    - Usuarios
    - Clientes
    - EstadosPedidos
    - ValoresSN
  columns:
    Id:
      title: N.Pedido
      visible: true
      updatable: false
      filter: YES
      list: YES
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Fecha:
      title: Fecha
      filter: YES
      list: YES
      visible: true
      updatable: false
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }      
    IdSucursal:
      title: Tienda
      filter: NO
      list: YES
      visible: true
      updatable: false
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: Tienda, entity: Sucursales, method: fetchAll, params: Nombre, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IdCliente:
      title: Cliente
      filter: NO
      list: YES
      visible: true
      updatable: false
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 3, caption: Cliente (%), entity: Clientes, method: null, params: RazonSocial, type: input }
      validator: { nullable: NO, type: integer, length: '25', min: null, max: null, message: 'Valor Requerido' }
    IdEstado:
      title: Estado
      filter: NO
      list: NO
      visible: true
      updatable: false
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 4, caption: Estado, entity: EstadosPedidos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '25', min: null, max: null, message: 'Valor Requerido' }
    NItems:
      title: NItems
      filter: YES
      list: YES
      visible: true
      updatable: false
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: decimal, length: '4', min: null, max: null, message: 'Valor Requerido' }
    Importe:
      title: Importe
      filter: YES
      list: YES
      visible: true
      updatable: false
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: currency, length: '10', min: null, max: null, message: 'Valor Requerido' }
    IdUsuario:
      title: Usuario
      filter: NO
      list: YES
      visible: true
      updatable: false
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 2, caption: Usuario, entity: Usuarios, method: fetchAll, params: Nombre, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '20', min: null, max: null, message: 'Valor Requerido' }
    AvisoRecepcionParcial:
      title: Aviso Recepción Parcial
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 5, caption: Aviso Recepción Parcial, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '2', min: null, max: null, message: 'Valor Requerido' }      
    Observations:
      title: Observaciones
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: false, min: null, max: null, message: 'Valor Requerido' }
    PrimaryKeyMD5:
      title: PrimaryKeyMD5
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    IsDefault:
      title: IsDefault
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 5, caption: IsDefault, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    IsSuper:
      title: IsSuper
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 6, caption: IsSuper, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    CreatedBy:
      title: CreatedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    CreatedAt:
      title: CreatedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    ModifiedBy:
      title: ModifiedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    ModifiedAt:
      title: ModifiedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    Deleted:
      title: Deleted
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 7, caption: Deleted, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    DeletedBy:
      title: DeletedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    DeletedAt:
      title: DeletedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    PrintedBy:
      title: PrintedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    PrintedAt:
      title: PrintedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    EmailedBy:
      title: EmailedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    EmailedAt:
      title: EmailedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
