# Module: FormasPago
# Document : modules/FormasPago/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 14.06.2015 19:46:25
#
---
FormasPago:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Descripcion
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Descripcion
  fieldGeneratorMetatagDescription: Descripcion
  fieldGeneratorMetatagKeywords: Descripcion
  controller: FormasPago
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Formas de Pago
  id_video: formaspago
  url_video: null
  feature_list: true
  conection: datos
  entity: FormasPago
  table: AgtFormasPago
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  export: 'false'
  order_by:
    -
      title: 'Descripción a-z'
      criteria: 'Descripcion ASC'
    -
      title: 'Descripción z-a'
      criteria: 'Descripcion DESC'
  search_default: Id
  referenced_entities:
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Descripcion:
      title: Descripción
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    NumeroVctos:
      title: Numero Vctos
      filter: true
      list: true
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    DiaPrimerVcto:
      title: Día Primer Vcto
      filter: true
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    DiasIntervalo:
      title: Días Intervalo
      filter: true
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    CContable:
      title: Cta. Contable
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0000000000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    AnotarEnCaja:
      title: Anotar en Caja
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: AnotarEnCaja, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    RecargoFinanciero:
      title: Recargo Financiero
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    DescuentoFinanciero:
      title: Descuento Financiero
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
