# Module: Provincias
# Document : modules/Provincias/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 16.12.2014 22:23:06
#
---
Provincias:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IdPais
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IdPais
  fieldGeneratorMetatagDescription: IdPais
  fieldGeneratorMetatagKeywords: IdPais
  controller: Provincias
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true  
  favourite_control: false
  help_file: help.html.twig
  title: Provincias
  id_video: provincias
  url_video: null
  feature_list: true
  conection: emp  
  entity: Provincias
  table: AgtProvincias
  primarykey: Id
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Provincia a-z'
      criteria: 'Provincia ASC'
    -
      title: 'Provincia z-a'
      criteria: 'Provincia DESC'
  search_default: Id
  referenced_entities:
    - Paises
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IdPais:
      title: País
      filter: false
      list: false
      visible: false
      updatable: true
      default: '68'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter': { order: 1, caption: IdPais, entity: Paises, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Codigo:
      title: Código
      filter: false
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '5', min: null, max: null, message: 'Valor Requerido' }
    Provincia:
      title: Provincia
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
