# Module: FirmasContactos
# Document : modules/FirmasContactos/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 18.06.2015 22:39:21
#
---
FirmasContactos:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IdFirma
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IdFirma
  fieldGeneratorMetatagDescription: IdFirma
  fieldGeneratorMetatagKeywords: IdFirma
  controller: FirmasContactos
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: tru
  permission_control: tru
  favourite_control: false
  help_file: help.html.twig
  title: Contactos
  id_video: firmascontactos
  url_video: null
  feature_list: tru
  conection: datos
  entity: FirmasContactos
  table: AgtFirmasContactos
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  export: 'false'
  order_by:
    -
      title: 'Id a-z'
      criteria: 'Id ASC'
    -
      title: 'Id z-a'
      criteria: 'Id DESC'
  search_default: Id
  referenced_entities:
    - Firmas
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IdFirma:
      title: IdFirma
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: IdFirma, entity: Firmas, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Cargo:
      title: Cargo
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Nombre:
      title: Nombre
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: tru, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: tru, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Movil:
      title: Movil
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: tru, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: tru, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
