CpanVariables:
  translatable: false
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  title: 'Gestión de Variables Web y de Entorno'
  help_file: help.html.twig
  columns:

