# Module: Clientes
# Document : modules/Clientes/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 16.12.2014 22:23:04
#
---
Clientes:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: RazonSocial
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: RazonSocial
  fieldGeneratorMetatagDescription: RazonSocial
  fieldGeneratorMetatagKeywords: RazonSocial
  controller: Clientes
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Clientes
  id_video: clientes
  url_video: null
  feature_list: true
  export: true
  conection: 'datos'  
  entity: Clientes
  table: AgtClientes
  primarykey: Id
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Nombre a-z'
      criteria: 'RazonSocial ASC'
    -
      title: 'Nombre z-a'
      criteria: 'RazonSocial DESC'
  search_default: Id
  referenced_entities:
    - Sexos
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    RazonSocial:
      title: Nombre
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Nif:
      title: Nif
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '15', min: null, max: null, message: 'Valor Requerido' }
    Direccion:
      title: Dirección
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Pais:
      title: País
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: 'España'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Provincia:
      title: Provincia
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Poblacion:
      title: Población
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    CodigoPostal:
      title: Código Postal
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Movil:
      title: Móvil
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Sexo:
      title: Sexo
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 4, caption: Sexo, entity: Sexos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    Observations:
      title: Observations
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: false, min: null, max: null, message: 'Valor Requerido' }
    PrimaryKeyMD5:
      title: PrimaryKeyMD5
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    IsDefault:
      title: IsDefault
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 5, caption: IsDefault, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    IsSuper:
      title: IsSuper
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 6, caption: IsSuper, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    CreatedBy:
      title: CreatedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    CreatedAt:
      title: CreatedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    ModifiedBy:
      title: ModifiedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    ModifiedAt:
      title: ModifiedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    Deleted:
      title: Deleted
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 7, caption: Deleted, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    DeletedBy:
      title: DeletedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    DeletedAt:
      title: DeletedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    PrintedBy:
      title: PrintedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    PrintedAt:
      title: PrintedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    EmailedBy:
      title: EmailedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    EmailedAt:
      title: EmailedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
