# Module: Tarifas
# Document : modules/Tarifas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 05.08.2015 23:03:22
#
---
Tarifas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IdArticulo
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IdArticulo
  fieldGeneratorMetatagDescription: IdArticulo
  fieldGeneratorMetatagKeywords: IdArticulo
  controller: Tarifas
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: false
  favourite_control: false
  help_file: help.html.twig
  title: Tarifas
  id_video: tarifas
  url_video: null
  feature_list: true
  conection: datos
  entity: Tarifas
  table: AgtTarifas
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  export: 'false'
  order_by:
    -
      title: 'Id a-z'
      criteria: 'Id ASC'
    -
      title: 'Id z-a'
      criteria: 'Id DESC'
  search_default: Id
  referenced_entities:
    - Articulos
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IdArticulo:
      title: Artículo
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: IdArticulo, entity: Articulos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IdTarifa:
      title: Tarifa
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Precio:
      title: Precio
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
