# Module: Usuarios
# Document : modules/Usuarios/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 16.12.2014 22:23:06
#
---
Usuarios:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Nombre
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Nombre
  fieldGeneratorMetatagDescription: Nombre
  fieldGeneratorMetatagKeywords: Nombre
  controller: Usuarios
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Usuarios
  id_video: usuarios
  url_video: null
  feature_list: true
  export: true
  conection: emp  
  entity: Usuarios
  table: AgtUsuarios
  primarykey: Id
  linkBy: ''
  records_per_page: 10
  order_by:
    - {title: 'Apellidos a-z', criteria: 'Apellidos ASC'}
    - {title: 'Apellidos z-a', criteria: 'Apellidos DESC'}
  search_default: Id
  referenced_entities:
    - Perfiles
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Apellidos:
      title: Apellidos
      filter: true
      list: yes
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Nombre:
      title: Nombre
      filter: true
      list: yes
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    DNI:
      title: DNI
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '15', min: null, max: null, message: 'Valor Requerido' }
    Direccion:
      title: Dirección
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Pais:
      title: País
      filter: true
      list: false
      visible: false
      updatable: true
      default: 'España'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Provincia:
      title: Provincia
      filter: true
      list: false
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Poblacion:
      title: Población
      filter: true
      list: false
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    CodigoPostal:
      title: Código Postal
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Movil:
      title: Móvil
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: true
      list: true
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Password:
      title: Password
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    TokenLogin:
      title: TokenLogin
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    IdPerfil:
      title: Perfil
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 4, caption: Perfil, entity: Perfiles, method: fetchAll, params: Perfil, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Activo:
      title: Activo
      filter: false
      list: true
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 6, caption: Activo, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '2', min: null, max: null, message: 'Valor Requerido' }
    NLogin:
      title: NLogin
      filter: true
      list: true
      visible: true
      updatable: false
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    UltimoLogin:
      title: Último Login
      filter: true
      list: true
      visible: true
      updatable: false
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
