# Module: Empresas
# Document : modules/Empresas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 14.06.2015 17:11:50
#
---
Empresas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: RazonSocial
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: RazonSocial
  fieldGeneratorMetatagDescription: RazonSocial
  fieldGeneratorMetatagKeywords: RazonSocial
  controller: Empresas
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Empresas
  id_video: empresas
  url_video: null
  feature_list: true
  entity: Empresas
  table: AgtEmpresas
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  export: 'false'
  order_by:
    -
      title: 'Razón Social a-z'
      criteria: 'RazonSocial ASC'
    -
      title: 'Razón Social z-a'
      criteria: 'RazonSocial DESC'
  search_default: Id
  referenced_entities:
    - Municipios
    - Provincias
    - Paises
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    RazonSocial:
      title: Razón Social
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Cif:
      title: Cif
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '15', min: null, max: null, message: 'Valor Requerido' }
    Direccion:
      title: Dirección
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    IdMunicipio:
      title: Municipio
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: IdMunicipio, entity: Municipios, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    CodigoPostal:
      title: Código Postal
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    IdProvincia:
      title: Provincia
      filter: false
      list: true
      visible: true
      updatable: true
      default: '18'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 2, caption: IdProvincia, entity: Provincias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IdPais:
      title: País
      filter: false
      list: false
      visible: false
      updatable: true
      default: '68'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 3, caption: IdPais, entity: Paises, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Web:
      title: Web
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Iban:
      title: Iban
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '34', min: null, max: null, message: 'Valor Requerido' }
    Bic:
      title: Bic
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '11', min: null, max: null, message: 'Valor Requerido' }
    SufijoRemesas:
      title: Sufijo Remesas
      filter: true
      list: false
      visible: true
      updatable: true
      default: '000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '3', min: null, max: null, message: 'Valor Requerido' }
    DigitosCuentaContable:
      title: Dígitos Cuenta Contable
      filter: true
      list: false
      visible: true
      updatable: true
      default: '10'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: integer, length: '2', min: null, max: null, message: 'Valor Requerido' }
    RegistroMercantil:
      title: Registro Mercantil
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    LicenciaActividad:
      title: Licencia Actividad
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Observations:
      title: Observations
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: false, min: null, max: null, message: 'Valor Requerido' }

