# Module: Familias
# Document : modules/Familias/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 18.06.2015 21:32:23
#
---
Familias:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IdFirma
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IdFirma
  fieldGeneratorMetatagDescription: IdFirma
  fieldGeneratorMetatagKeywords: IdFirma
  controller: Familias
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Familias de Artículos
  id_video: familias
  url_video: null
  feature_list: true
  conection: datos
  entity: Familias
  table: AgtFamilias
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  export: 'false'
  order_by:
    -
      title: 'Descripción a-z'
      criteria: 'IdFirma ASC, Descripcion ASC'
    -
      title: 'Descripción z-a'
      criteria: 'IdFirma ASC, Descripcion DESC'
  search_default: Id
  referenced_entities:
    - Firmas
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IdFirma:
      title: Firma
      filter: false
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: Firma, entity: Firmas, method: fetchAll, params: RazonSocial, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Descripcion:
      title: Descripción
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
